from __future__ import annotations

from pathlib import Path

from patchly.config import WORKSPACE, PatchlyConfig
from patchly.github_client import (
    create_branch,
    create_commit,
    create_pr,
    get_branch_sha,
    get_file_content,
)
from patchly.llm import chat


def generate_fix(
    file_path: str,
    issue_description: str,
    config: PatchlyConfig,
) -> str | None:
    content = get_file_content(file_path)
    if content is None:
        return None

    prompt = (
        f"Fix this issue in {file_path}:\n\n"
        f"Issue: {issue_description}\n\n"
        f"Current code:\n```\n{content[:8000]}\n```\n\n"
        "Return ONLY the corrected file content. No explanations."
    )

    return chat([{"role": "user", "content": prompt}], config)


def apply_fix_as_pr(
    file_path: str,
    new_content: str,
    branch_name: str,
    config: PatchlyConfig,
) -> str | None:
    import base64
    import json
    import httpx

    from patchly.github_client import API, HEADERS, GITHUB_REPOSITORY

    sha = get_branch_sha("main")
    ref_resp = httpx.post(
        f"{API}/repos/{GITHUB_REPOSITORY}/git/refs",
        headers=HEADERS,
        json={"ref": f"refs/heads/{branch_name}", "sha": sha},
        timeout=15,
    )
    if ref_resp.status_code != 201:
        return None

    try:
        current = get_file_content(file_path, "main")
        current_sha = ""
        if current is not None:
            info = httpx.get(
                f"{API}/repos/{GITHUB_REPOSITORY}/contents/{file_path}",
                headers=HEADERS,
                timeout=15,
            )
            if info.status_code == 200:
                current_sha = info.json().get("sha", "")

        put = httpx.put(
            f"{API}/repos/{GITHUB_REPOSITORY}/contents/{file_path}",
            headers=HEADERS,
            json={
                "message": f"patchly: auto-fix {file_path}",
                "content": base64.b64encode(new_content.encode()).decode(),
                "sha": current_sha,
                "branch": branch_name,
            },
            timeout=15,
        )
        if put.status_code not in (200, 201):
            return None
    except Exception:
        return None

    pr = create_pr(
        title=f"Patchly: Fix {file_path}",
        body=f"Automated fix generated by Patchly.\n\n`{file_path}` was modified.",
        head=branch_name,
    )
    return pr.get("html_url")
