from __future__ import annotations

import base64

from patchly.config import PatchlyConfig
from patchly.github_client import (
    GITHUB_REPOSITORY,
    _github_api,
    create_branch,
    create_pr,
    get_branch_sha,
    get_file_content,
    get_default_branch,
)
from patchly.llm import chat


def generate_fix(
    file_path: str,
    issue_description: str,
    config: PatchlyConfig,
) -> str | None:
    content = get_file_content(file_path)
    if content is None:
        return None

    prompt = (
        f"Fix this issue in {file_path}:\n\n"
        f"Issue: {issue_description}\n\n"
        f"Current code:\n```\n{content[:8000]}\n```\n\n"
        "Return ONLY the corrected file content. No explanations."
    )

    return chat([{"role": "user", "content": prompt}], config)


def apply_fix_as_pr(
    file_path: str,
    new_content: str,
    branch_name: str,
    config: PatchlyConfig,
) -> str | None:
    try:
        sha = get_branch_sha(get_default_branch())
        if not sha:
            return None

        if not create_branch(branch_name, sha):
            return None

        file_info = _github_api(
            method="GET",
            endpoint=f"/repos/{GITHUB_REPOSITORY}/contents/{file_path}",
        )
        current_sha = file_info.json().get("sha", "") if file_info.status_code == 200 else ""

        encoded_content = base64.b64encode(new_content.encode()).decode()
        update_response = _github_api(
            method="PUT",
            endpoint=f"/repos/{GITHUB_REPOSITORY}/contents/{file_path}",
            json={
                "message": f"patchly: auto-fix {file_path}",
                "content": encoded_content,
                "sha": current_sha,
                "branch": branch_name,
            },
        )
        if update_response.status_code not in (200, 201):
            return None

        pr = create_pr(
            title=f"Patchly: Fix {file_path}",
            body=f"Automated fix generated by Patchly.\n\n`{file_path}` was modified.",
            head=branch_name,
        )
        return pr.get("html_url")
    except Exception:
        return None